---
title: "Harvard Enrollment"
author: "Niel Schrage"
date: "4/10/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# loaded libraries

library(tidyverse)
library(ggthemes)
library(fs)
library(lubridate)
library(viridis)
library(gganimate)
library(ggplot2)
library(janitor)
library(readxl)
library(ggrepel)


```

```{r load_data, echo=FALSE}

# downloaded the xlsx file from the harvard website for spring enrollments in
# 2017, 2018, and 2019

download.file(url="http://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_2017_03_07_final_0.xlsx", destfile = "reg_2017.xlsx", mode = "wb" )

download.file(url="https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_03.06.18.xlsx", destfile = "reg_2018.xlsx", mode = "wb" )

download.file(url="https://registrar.fas.harvard.edu/files/fas-registrar/files/class_enrollment_summary_by_term_3.22.19.xlsx", destfile = "reg_2019.xlsx", mode = "wb" )

# read in the xlsx files for the spring enrollment data from 2017, 2018, and
# 2019. skipped three rows that were not useful. used mutate to add a column to
# each with the year, to make it easier to come to graph later. I also started
# data cleaning. for each of the years, I used the clean_names function from the
# janitor library to make the data easier to work with. I also filtered out any
# rows that did not have a result for course name.

x_2017 <- read_excel("reg_2017.xlsx", skip = 3) %>% 
  mutate(year = 2017) %>% 
  clean_names() %>% 
  filter(! is.na(course_name)) 

x_2018 <- read_excel("reg_2018.xlsx", skip = 3) %>% 
  mutate(year = 2018) %>% 
  clean_names() %>% 
  filter(! is.na(course_name)) 

x_2019 <- read_excel("reg_2019.xlsx", skip = 3) %>% 
  mutate(year = 2019) %>% 
  clean_names() %>% 
  filter(! is.na(course_name)) 
 

# deleted the xlsx files after loading the data into my r session

fs::file_delete(c("reg_2017.xlsx","reg_2018.xlsx", "reg_2019.xlsx")) 

# joined the data frames together using bind rows, like we did in class for the NYT data

enrollment <- bind_rows(x_2017, x_2018, x_2019)

```

```{r explore_data, echo=FALSE}

# i'm interested in seeing how department enrollment changes each year. I
# originally wanted to take data from 1999, 2009, and 2019 to paint the picture
# of the massive move from gov to computer science.

top_departments <- enrollment %>% 
  
  # select the variables to work with
  
  select(course_department, course_title, year, u_grad) %>% 
  
  # filter out gen eds
  
  filter(course_department != "General Education") %>% 
  
  # relevel the courses so that they are in descending order -- has to be before group by 
  
  mutate(course_department = fct_relevel(course_department, c("Economics", "Computer Science", "Mathematics", "Psychology", "Government"))) %>% 
  
  # group by department and year
  
  group_by(course_department, year) %>%
  
  # calculate the total number of undergrades in each department
  
  summarize(total = sum(u_grad)) %>% 
  
  # arrange highest to lowest
  
  arrange(desc(total)) %>% 
  
  # view the top departments 
  #"Economics", "Computer Science", "Mathematics", "Psychology", "Government"
  
  slice(1:6) %>% 

  # filter so just the top departments are included. 
  
  filter(course_department %in%c("Economics", "Computer Science", "Mathematics", "Psychology", "Government")) 
  
```

```{r show_data, echo=FALSE, results='asis'}
top_departments %>% 
  
  # create plot with x as the department (we manually ordered that earlier), y
  # is the total number of undergraduates, and fill = ..x.. to map the color
  # package
  
  ggplot(aes(x = course_department, y = total)) +
  
    # turned off the legend, wasn't helpful
  
    geom_col(show.legend = FALSE, aes(fill = ..x..)) +
  
    # added title, subtitle, caption for ease of understanding
  
    labs(title = "Harvard's Top Departments by Enrollment 2017 - 2019",
       
      # included updating year {here}
      
      subtitle = "Year: {closest_state}",
      caption = "Harvard Registrar 2017 - 2019")+
   
    # added X and Y axis labels  
    
    xlab("Top Academic Departments Between 2017 - 2019") + 
    ylab("Total Undergraduate Enrollment") +
   
    # manually scaled the y axis breaks to make the graph easier to understand
    
    scale_y_continuous(breaks = seq(0, 2500, by = 250)) +
  
    # colored each department to highlight diffences... used one of the options
    # from Viridis
    
    scale_fill_viridis(guide = FALSE, option = "E") +
    
    # applied the minimalist tufte theme that I am a fan of. 
  
    theme_tufte() +
    
    # gganimated the graph to progressively show the total by year

    transition_states(year) +
    
    # added cubic in and out to make the time between movement slower
      
    ease_aes('cubic-in-out')

```

